[package]
name        = "hellouniverse"
description = "A simple Hello Universe program"
version     = "1.0.0"
flix        = "0.34.0"
license     = "Apache-2.0"
authors     = ["John Doe <john@example.com"]

[dependencies]
"github:magnus-madsen/helloworld" = "1.3.0"
